version: '3.5'
services:
  imagebuilder:
    image: "openwrtorg/imagebuilder:x86-64-19.07.7"
    container_name: imagebuilder
    env_file:
     - ./.env
    volumes:
     - ./bin:/home/build/openwrt/bin
     - ./DIY.sh:/home/build/openwrt/DIY.sh
     - ./system-custom.tpl:/home/build/openwrt/system-custom.tpl
     - ./build.sh:/home/build/openwrt/build.sh
     - ./files:/home/build/openwrt/files
    command: "./build.sh"