version: "3.5"
services:
  imagebuilder_x86_64_19_07:
    image: "openwrtorg/imagebuilder:x86-64-19.07.7"
    container_name: imagebuilder_x86_64_19_07
    environment:
      - TARGET=x86_64
      - OPENWRT_VERSION=19.07
    env_file:
      - ./.env
    volumes:
      - ./bin/19_07:/home/build/openwrt/bin
      - ./diy_files:/home/build/openwrt/diy_files
      - ./build.sh:/home/build/openwrt/build.sh
    command: "./build.sh"

  imagebuilder_x86_64_21_02:
    image: "openwrtorg/imagebuilder:x86-64-21.02-SNAPSHOT"
    # image: "openwrtorg/imagebuilder:x86-64-openwrt-21.02"
    container_name: imagebuilder_x86_64_21_02
    environment:
      - TARGET=x86_64
      - OPENWRT_VERSION=21.02
    env_file:
      - ./.env
    volumes:
      - ./bin/21_02:/home/build/openwrt/bin
      - ./diy_files:/home/build/openwrt/diy_files
      - ./build.sh:/home/build/openwrt/build.sh
    command: "./build.sh"

  imagebuilder_rockchip_21_02:
    image: "openwrtorg/imagebuilder:rockchip-armv8-21.02-SNAPSHOT"
    container_name: imagebuilder_rockchip_21_02
    env_file:
      - ./.env
    environment:
      - TARGET=rockchip
      - OPENWRT_VERSION=21.02
    volumes:
      - ./bin/21_02:/home/build/openwrt/bin
      - ./diy_files:/home/build/openwrt/diy_files
      - ./build.sh:/home/build/openwrt/build.sh
    command: "./build.sh"

  imagebuilder_ar71xx_nand:
    image: "openwrtorg/imagebuilder:ar71xx-nand-19.07.7"
    container_name: imagebuilder_ar71xx_nand
    environment:
      - TARGET=ar71xx_nand
      - OPENWRT_VERSION=19.07
    env_file:
      - ./.env
    volumes:
      - ./bin/19_07:/home/build/openwrt/bin
      - ./diy_files:/home/build/openwrt/diy_files
      - ./build.sh:/home/build/openwrt/build.sh
    command: "./build.sh"

  imagebuilder_ar71xx_nand_21:
    image: "openwrtorg/imagebuilder:ath79-nand-21.02-SNAPSHOT"
    container_name: imagebuilder_ar71xx_nand_21
    environment:
      - TARGET=ar71xx_nand
      - OPENWRT_VERSION=21.02
    env_file:
      - ./.env
    volumes:
      - ./bin/21_02:/home/build/openwrt/bin
      - ./diy_files:/home/build/openwrt/diy_files
      - ./build.sh:/home/build/openwrt/build.sh
    command: "./build.sh"
