#!/bin/sh

echo "iface $INTERFACE $ACTION detected..."

[ "$ACTION" = "ifup" -a "$INTERFACE" = "wan" ] && {

    sleep 3

    ps | grep mihomo | grep nobody
    if [ $? -eq 0 ]; then
        logger "mihomo is running"
    else
        if [ ! -f /root/.mihomo_first_boot ]; then
            logger "First boot detected, starting mihomo..."

            uci -q set mihomo.config.enabled=1
            uci -q commit mihomo

            /etc/init.d/mihomo start

            touch /root/.mihomo_first_boot
        else
            logger "Not first boot, mihomo start according to config"
        fi
    fi
}