#!/bin/sh

ps | grep openclash | grep nobody

[ "$ACTION" = "ifup" -a "$INTERFACE" = "wan" ] && {
    logger "iface wan up detected..."
    
    if [ $? -eq 0 ]; then
        logger "OpenClash is running"
    else
        if [ ! -f /root/.first_boot ]; then
            logger "First boot detected, starting OpenClash..."

            /usr/share/openclash/openclash_ipdb.sh
            /usr/share/openclash/openclash_geoip.sh
            /usr/share/openclash/openclash_chnroute.sh

            /etc/init.d/openclash start

            touch /root/.first_boot
            exit 0
        fi
    fi
}