# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: ["master"]
    paths:
      - "**"
      - "!*.md"
      - "!changelog.txt"

  pull_request:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
          - "immortalwrt/imagebuilder:x86-64-openwrt-24.10.2"
          - "immortalwrt/imagebuilder:x86-64-openwrt-23.05.4"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup environment
        run: |
          echo "PPPOE_USERNAME=123" >> modules/pppoe/.env
          echo "PPPOE_PASSWORD=123" >> modules/pppoe/.env
          echo "LAN_IP=192.168.1.1" >> modules/lan/.env
          echo "CLASH_CONFIG_URL=https://gist.github.com/EkkoG/20a52db0169c4a4769689521b1c5500e/raw/cf61a9397d0bdbd5b6bbad8fbb388ec851116470/clash_example.yaml" >> modules/openclash/.env
          echo "CONFIG_TARGET_KERNEL_PARTSIZE=16" > .env
          echo "CONFIG_TARGET_ROOTFS_PARTSIZE=256" >> .env
          echo "MODULES=openclash openclash-as-default" >> .env
          echo "LOG_ENABLE=1" >> .env

      - name: Build image ${{ matrix.image }}
        run: |
          ./run.sh --image=${{ matrix.image }} --mirror=mirrors.cernet.edu.cn
